### PR TITLE
Improve typescript typing

### PR DESCRIPTION
**Pull request by sxwei123**
Add type definitions to `opts`, `opts.cmp` and `opts.cycles`.

### CODE REVIEW

**Comment by epoberezkin** [comment]
Hey @sxwei123 - looks cool :)

Is this PR opened by mistake or you propose to merge your fork back in?

**Comment by epoberezkin** [comment]
Most likely you just continued committing to the same branch where the original PR was opened from - correct?...

**Comment by sxwei123** [comment]
@epoberezkin 
Oh sorry. I think I did something wrong.
I created a new [stringify package](https://github.com/sxwei123/quick-stable-stringify) with Typescript and es6 based on your code. 
Please closed this PR.

**Comment by sxwei123** [comment]
Create another PR to improve the comparator function typing:
https://github.com/epoberezkin/fast-json-stable-stringify/pull/47

**Comment by epoberezkin** [comment]
No problem - I figured it was accidental - thanks for confirming!

**Pull request closed without merging**
